apiVersion: v1
kind: Secret
metadata:
  name: hello-secret
  labels:
    app: hello
type: Opaque
# `stringData` accepte des valeurs en clair, K8s les encodera en base64 à l'apply.
# (Pour la prod, on utiliserait Sealed Secrets, SOPS, Vault, Azure Key Vault, etc.)
stringData:
  APP_USER:     "ange.admin"
  APP_PASSWORD: "S3cretD3mo!2026"
