apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-pvc
  labels:
    app: hello
spec:
  accessModes:
    - ReadWriteOnce        # un seul node en lecture/écriture 
  resources:
    requests:
      storage: 1Gi

  # storageClassName: standard
